# Config for torchtune/_cli/eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune eval --config torchtune/_cli/eval_configs/default_eval_config.yaml

# Model Arguments
model:
  _component_: torchtune.models.llama2.llama2_7b


model_checkpoint: /tmp/llama2/model.ckpt

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /tmp/llama2/tokenizer.model


# Environment
device: cuda
seed: 217

# EleutherAI specific eval args
tasks: ["hellaswag"]
limit: null
