# Config for torchtune/_cli/eval.py
#
# To launch, run the following command from root:
#    python torchtune/_cli/eval.py --config torchtune/_cli/eval_configs/default_eval_config.yaml

# Model Arguments
model:
  _component_: torchtune.models.llama2.llama2_7b


model_checkpoint: /home/rvarm1/local/dev/assets/llama2-7b-01242024

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /home/rvarm1/local/dev/assets/tokenizer.model


# Environment
device: cuda
seed: 217

# EleutherAI specific eval args
tasks: ["hellaswag"]
limit: null
