# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command:
#    tune run eleuther_eval --config mistral_small/evaluation

output_dir: ./ # Not needed

# Model Arguments
model:
  _component_: torchtune.models.mistral_small.mistral_24b

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Mistral-Small-24B-Base-2501/
  checkpoint_files: [
    model-00001-of-00010.safetensors,
    model-00002-of-00010.safetensors,
    model-00003-of-00010.safetensors,
    model-00004-of-00010.safetensors,
    model-00005-of-00010.safetensors,
    model-00006-of-00010.safetensors,
    model-00007-of-00010.safetensors,
    model-00008-of-00010.safetensors,
    model-00009-of-00010.safetensors,
    model-00010-of-00010.safetensors
  ]
  output_dir: ${output_dir}
  model_type: MISTRAL
resume_from_checkpoint: False

# Tokenizer
tokenizer:
  _component_: torchtune.models.mistral.mistral_tokenizer
  path: /tmp/Mistral-Small-24B-Base-2501/tokenizer.model
  max_seq_len: null

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2"]
limit: null
max_seq_length: 4096
batch_size: 8
enable_kv_cache: True

# Quantization specific args
quantizer: null
