# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config qwen3/evaluation

output_dir: ./ # Not needed

# Model Arguments
model:
  _component_: torchtune.models.qwen3.qwen3_0_6b_instruct

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Qwen3-0.6B
  checkpoint_files: [
    model.safetensors,
  ]
  output_dir: ${output_dir}
  model_type: QWEN3

# Tokenizer
tokenizer:
  _component_: torchtune.models.qwen3.qwen3_tokenizer
  path: /tmp/Qwen3-0.6B/vocab.json
  merges_file: /tmp/Qwen3-0.6B/merges.txt
  max_seq_len: null

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2"]
limit: null
max_seq_length: 4096
batch_size: 8
enable_kv_cache: True

# Quantization specific args
quantizer: null
