# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command:
#    tune run generate --config qwen2/generation

# Model Arguments
model:
  _component_: torchtune.models.qwen2.qwen2_7b

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Qwen2-7B-Instruct
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  output_dir: ./ # Not needed
  model_type: QWEN2

# Tokenizer
tokenizer:
  _component_: torchtune.models.qwen2.qwen2_tokenizer
  path: /tmp/Qwen2-7B-Instruct/vocab.json
  merges_file: /tmp/Qwen2-7B-Instruct/merges.txt
  max_seq_len: null

device: cuda
dtype: bf16

seed: 1234

# Generation arguments; defaults taken from gpt-fast
prompt: Tell me a joke.
instruct_template: null
chat_format: null
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

enable_kv_cache: True

quantizer: null
