# Config for torchtune/_cli/eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune custom_eval --config instruct_custom_eval

# Model Arguments
model:
  _component_: torchtune.models.llama2.llama2_7b


model_checkpoint: /tmp/llama2/model.ckpt

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /tmp/llama2/tokenizer.model

# Environment
device: cuda
seed: 217

# EleutherAI specific eval args
tasks: ["truthfulqa", "mmlu"]
limit: 100
