# Config for EleutherEvalRecipe in eluether_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune eleuther_eval --config llama2_eleuther_eval

# Model Arguments
model:
  _component_: torchtune.models.llama2.llama2_7b

checkpointer:
  _component_: torchtune.utils.FullModelTorchTuneCheckpointer
  checkpoint_dir: /tmp/llama/
  checkpoint_files: [finetuned_model.pt]
  output_dir: /tmp/llama/
  model_type: LLAMA2

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /tmp/llama/tokenizer.model

# Environment
device: cuda
dtype: bf16
seed: 217

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2"]
limit: null
max_seq_length: 4096
