# Config for torchtune/_cli/eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune custom_eval --config instruct_custom_eval

# Model Arguments
model:
  _component_: torchtune.models.llama2.llama2_7b

checkpointer:
  _component_: torchtune.utils.FullModelTorchTuneCheckpointer
  checkpoint_dir: ./
  checkpoint_files: [qlora_trained.pt]
  recipe_checkpoint: null
  output_dir: ./
  model_type: LLAMA2

model_checkpoint: ./qlora_trained.pt

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: ./tokenizer.model

# Environment
device: cuda
dtype: fp32
seed: 217

# EleutherAI specific eval args
tasks: ["truthfulqa"]
limit: 100
