
# Model arguments
model:
  _component_: torchtune.models.llama2.llama2_7b

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: /tmp/llama2/
  checkpoint_files: [meta_model_0.pt]
  output_dir: /tmp/llama2/
  model_type: LLAMA2

device: cuda
dtype: bf16
seed: 1234

# Quantization Arguments
quantization_mode: 4w
