# This tests a conversion of Llama2 7b FAIR checkpoint to a TorchTune-supported native checkpoint
# It runs on a daily cadence at the end of each day

name: large scale conversion script test

on:
  schedule:
    - cron: "0 0 * * *" # Run at the end of every day
  workflow_dispatch:


concurrency:
  group: conversion-script-test-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  conversion_script_test:
    runs-on: 32-core-ubuntu
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: configure aws credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_torchtune_pytorch-multimodal
          aws-region: us-east-1
      - name: Download files from S3
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 14400
          command: |
            sudo swapoff -a
            sudo fallocate -l 64G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            python -m pip install awscli==1.32.6
            mkdir -p /tmp/test-artifacts
            aws s3 cp s3://pytorch-multimodal/llama2-7b/consolidated.00.pth /tmp/test-artifacts/llama2-7b-fair
      - name: Install dependencies
        run: |
          python -m pip install torch
          python -m pip install -e ".[dev]"
      - name: Run conversion test
        run: |
          pytest tests/torchtune/_cli/test_convert_checkpoint.py --large-scale True
