name: Lint

on:
  pull_request:
  workflow_dispatch:


concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  lint:
    if: github.repository_owner == 'pytorch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install lint utilities
        run: |
          python -m pip install pre-commit
          pre-commit install-hooks
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f # v45.0.6
      - name: Lint modified files
        run: pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}
