name: Lint

on:
  pull_request:


defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install lint utilities
        run: |
          python -m pip install pre-commit
          pre-commit install-hooks
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          prNumber: ${{ github.event.number }}
          output: ' '
      - name: Lint modified files
        run: pre-commit run --files ${{ steps.file_changes.outputs.files }}
